package GameStructure;

public interface GameNetwork {
	int 
	PORT_SERVER_INGAME = 010,
	PORT_PLAYER_CLIENT_INGAME_1 = 3323, 
	PORT_PLAYER_CLIENT_INGAME_2 = 6278,
	PORT_SERVER_LOBBY = 011,
	PORT_PLAYER_CLIENT_LOBBY_1 = 3324, 
	PORT_PLAYER_CLIENT_LOBBY_2 = 6279;
}
